# Generated by Django 5.0.4 on 2024-04-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Enviado', 'Enviado'), ('Em Análise', 'Em Análise'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
        ),
    ]
