# Generated by Django 5.0.4 on 2024-04-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=20)),
                ('educacao', models.CharField(max_length=255)),
                ('experiencia_profissional', models.CharField(max_length=255, verbose_name='experiência profissional')),
                ('nascimento', models.DateField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
